import Link from 'next/link';
import { Lock, ArrowLeft } from 'lucide-react';
import { AnimatedBackground } from '@/components/ui/animated-background';

export default function PrivacyPage() {
  return (
    <main className="min-h-screen w-full relative flex flex-col items-center overflow-hidden selection:bg-primary/20 bg-background text-foreground pb-20">
      <AnimatedBackground />

      <div className="container relative z-10 px-4 md:px-6 flex flex-col items-start space-y-8 pt-12 max-w-4xl mx-auto">
        <Link 
          href="/" 
          className="inline-flex items-center text-sm font-medium text-muted-foreground hover:text-primary transition-colors mb-4"
        >
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Home
        </Link>
        
        <div className="space-y-4">
          <div className="inline-flex items-center rounded-full border border-white/10 bg-white/5 px-3 py-1 text-sm font-medium backdrop-blur-md mb-2">
            <Lock className="h-4 w-4 text-primary mr-2" />
            Legal Documentation
          </div>
          <h1 className="text-4xl md:text-5xl font-bold tracking-tighter">Privacy Policy</h1>
          <p className="text-muted-foreground">Last updated: March 2026</p>
        </div>

        <div className="prose prose-invert prose-p:text-muted-foreground prose-headings:text-foreground w-full max-w-none bg-white/5 border border-white/10 p-8 rounded-2xl backdrop-blur-sm shadow-2xl">
          <h2>1. Our True Zero-Knowledge Philosophy</h2>
          <p>
            Voyonata is not a traditional tech company. We do not monetize your data because, mathematically speaking, we cannot read it. 
            Your privacy is enforced by cryptography, not just policy.
          </p>

          <h2>2. Data We Collect</h2>
          <p>
            We collect the absolute minimum required to operate an AI Travel Planner:
          </p>
          <ul>
            <li><b>Email Address:</b> Used strictly as a unique identifier and communication channel.</li>
            <li><b>Device Fingerprints:</b> We hash your IP Address and User-Agent together to cryptographically bind your active session tokens. We discard the raw IP immediately after hashing.</li>
            <li><b>Hardware Passkeys:</b> We store Public Keys generated by your FIDO2 Authenticators (e.g. TouchID, standard YubiKey bindings). The Private Key never leaves your hardware.</li>
            <li><b>Travel Prompts:</b> We process your destination queries linearly through our AI models to return your itinerary.</li>
          </ul>

          <h2>3. Data We NEVER Collect</h2>
          <p>
            Due to our Client-Side WebCrypto hashing architecture, your plaintext passwords are mathematically destroyed in your web browser before the network request is even transmitted.
            We see nothing but SHA-256 hashes, securing your privacy aggressively against both external breaches and internal compromise.
          </p>

          <h2>4. Third-Party Sharing</h2>
          <p>
            Voyonata does not sell, rent, or lease your AI itineraries or personal identifiers to third parties. All sensitive payload manipulation is directly governed by our open security envelope.
          </p>
          
          <h2>5. Your Rights</h2>
          <p>
            Under GDPR, CCPA, and basic human decency, you possess the right to be forgotten. You may delete your account at any time, which triggers a cascading deletion of your data across our Postgres database and Redis caches.
          </p>
        </div>

      </div>
    </main>
  );
}
